name: muser_ui
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  intl: ^0.16.1
  flutter_spinkit: ^4.1.2+1
  audioplayers: ^0.15.1
  path_provider: ^1.6.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  get_it: ^4.0.2
  flutter_secure_storage: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/music/BBQ_song.mp3
    - assets/music/Bells_and_Drum.mp3
    - assets/music/Boomwhacker_Chant.mp3
    - assets/music/Bubbles_in_the_Air.mp3
    - assets/music/Bubble_Song.mp3
    - assets/music/Can_you_move_like_this.mp3
    - assets/music/Come_and_play.mp3
    - assets/music/Copy_Cat.mp3
    - assets/music/Do_This.mp3
    - assets/music/Drum_in_the_Middle_of_the_room.mp3
    - assets/music/Everybody_has_a_Name.mp3
    - assets/music/Feelings.mp3
    - assets/music/Feel_it.mp3
    - assets/music/Gathering_Drum.mp3
    - assets/music/Get_up_March_out.mp3
    - assets/music/Goodbye_My_Friend.mp3
    - assets/music/Hello.mp3
    - assets/music/Hello_And_Welcome.mp3
    - assets/music/Hello_to_You.mp3
    - assets/music/Hey_Ho_It_s_Time_to_Go.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
